version: "3"

services:
  kong.products:
    image: pogs/kong-products
    container_name: kong-products
    hostname: kong.products
    build:
      context: ./products
    ports:
      - "52800:3000"
    environment:
      "PUBLIC_PORT": "52800"
  kong.users:
    image: pogs/kong-users
    container_name: kong-users
    hostname: kong.users
    build:
      context: ./users
    ports:
      - "52801:3000"
    environment:
      "PUBLIC_PORT": "52801"
  kong.transactions:
    image: pogs/kong-transactions
    container_name: kong-transactions
    hostname: kong.transactions
    build:
      context: ./transactions
    ports:
      - "52802:3000"
    environment:
      "PUBLIC_PORT": "52802"

# Kong Services
  kong:
    image: kong:0.11.2
    hostname: kong
    container_name: kong
    entrypoint: 
      - /bin/bash 
      - -c 
      - "echo \"Sleeping [5] for postgres startup\" && sleep 5 && echo \"Starting Kong\" && kong start"
    env_file: config/kong.env
    ports: 
      - 10000:8000 # HTTP Traffic for data plane
      - 10001:8443 # HTTPS Traffic for data plane
      - 10002:8001 # HTTP Traffic for control plane
      - 10003:8444 # HTTPS Traffic for control plane
    volumes:
      - vkong:/usr/local/kong
    links:
      - postgres
      - kong.products
      - kong.users
      - kong.transactions

  konga: 
    image: pantsel/konga:legacy
    hostname: konga
    container_name: konga
    entrypoint: 
      - /bin/bash 
      - -c 
      - "echo \"Sleeping [10] for postgres startup\" && sleep 10 && echo \"Starting Konga\"&&npm run production"
    env_file: config/konga.env
    ports:
      - 12000:1337
    volumes:
      - vkonga:/kongadata
    links:
      - postgres
      - kong
      
  postgres:
    image: postgres:10-alpine
    hostname: postgres
    container_name: postgres
    env_file: config/postgres.env
    ports: 
      - 11000:8080
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    external: true
  vkonga:
    external: true
  vkong:
    external: true