version: "3"

services:

  kong:
    image: kong:0.11.2
    hostname: kong
    container_name: kong
    entrypoint: 
      - /bin/bash 
      - -c 
      - "echo \"Sleeping [20] for postgres startup\" && sleep 20 && kong migrations up"
    env_file: config/kong.env
    volumes:
      - vkong:/usr/local/kong
    links:
      - postgres
      
  konga: 
    image: pantsel/konga:legacy
    hostname: konga
    container_name: konga
    entrypoint: 
      - /bin/bash 
      - -c 
      - "echo \"Sleeping [30] for postgres startup\" && sleep 30 && echo \"Starting konga\" && npm start"
    env_file: config/konga.env
    volumes:
      - vkonga:/kongadata
    links:
      - postgres
      - kong
    

  postgres:
    image: postgres:10-alpine
    hostname: postgres
    container_name: postgres
    env_file: config/postgres.env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      
volumes:
  pgdata:
    external: true
  vkonga:
    external: true
  vkong:
    external: true