version: "3"

services:

  kong:
    image: kong:0.11.2
    hostname: kong
    container_name: kong
    entrypoint: 
      - /bin/bash 
      - -c 
      - "echo \"Sleeping [25] for postgres startup\" && sleep 25 && kong migrations up"
    env_file: config/kong.env
    volumes:
      - ./kong-core:/usr/local/kong
    links:
      - postgres
      
  konga: 
    image: pantsel/konga:legacy
    hostname: konga
    container_name: konga
    entrypoint: 
      - /bin/bash 
      - -c 
      - "echo \"Sleeping [45] for postgres startup\" && sleep 45 && echo \"Starting konga\" && npm start"
    env_file: config/konga.env
    volumes:
      - ./konga:/kongadata
    links:
      - postgres
      - kong
    

  postgres:
    image: postgres:10-alpine
    hostname: kongdb
    container_name: kongdb
    env_file: config/postgres.env
    volumes:
      - pgdata:/var/lib/postgresql/data
      
volumes:
  pgdata:
     external: true