service: eshop-users
provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-1
  stage: prod
  apiGateway:
    restApiId:
      "Fn::ImportValue": EShopGW-restApiId
    restApiRootResourceId:
      "Fn::ImportValue": EShopGW-rootResourceId
functions:
  get-users:
    handler: handler.getUsers
    events:
      - http:
          path: users/list
          method: get
