service: eshop-transactions
provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-1
  stage: prod
  apiGateway:
    restApiId:
      "Fn::ImportValue": EShopGW-restApiId
    restApiRootResourceId:
      "Fn::ImportValue": EShopGW-rootResourceId
functions:
  get-transactions:
    handler: handler.getTransactions
    events:
      - http:
          path: transactions/list
          method: get
